language: cpp
services:
    - docker
git:
    depth: false
dist: focal
sudo: required
matrix:
    include:
        - env: TARGET_OS=debian.buster
script:
    - docker pull veyon/ci.${TRAVIS_OS_NAME}.${TARGET_OS}:latest || docker build -t veyon/ci.${TRAVIS_OS_NAME}.${TARGET_OS} ${TRAVIS_BUILD_DIR}/.ci/${TRAVIS_OS_NAME}.${TARGET_OS}/
    - docker run -v ${TRAVIS_BUILD_DIR}:/veyon:rw veyon/ci.${TRAVIS_OS_NAME}.${TARGET_OS} /bin/sh /veyon/.ci/${TRAVIS_OS_NAME}.${TARGET_OS}/script.sh /veyon /build
